version: '3'

services:
  nats:
    image: nats
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "-c /nats-config/nats.conf"
    volumes:
      - ./config:/nats-config